### ISSUE TITLE
Add support for https/443 to Atelier API

### ISSUE THREAD

**Issue by theflyingape** [doublefint/vscode-cos#3]
The default http/57772 is fine, but in healthcare IT department, we must have encryption enabled.
Thank you!

**Comment by ZitRos** [comment]
@theflyingape, hello.

Please, let me know whether you can connect with HTTPS now. Thanks!

**Comment by theflyingape** [comment]
I am encouraged by this commit, but I do not see any access log entry on the Apache-side of this change taking any effect:

"cos.conn": {
        "label": "Cassiopeia",
        "host": "cassiopeia.bidmc.harvard.edu",
        "port": 443,
        "username": "rhurst",
        "password": "************",
        "path": "/api/atelier/",
        "version": "v1",
        "ns": "DEV",
        "https": true
    }

It works only if I default this back to canned http/57772.  My access credentials are in good working order on the server-side:

[rhurst@cassiopeia ~]$ cache

Node: cassiopeia.bidmc.harvard.edu, Instance: CACHE

Username: rhurst
Password: *************
USER>zn "dev"

DEV>w $roles
%All

... client-side:
[rhurst@8ball ~]$ code -v
1.17.2
[rhurst@8ball ~]$ uname -a
Linux 8ball.bidmc.harvard.edu 4.13.5-200.fc26.x86_64 #1 SMP Thu Oct 5 16:53:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ZitRos** [comment]
Hi! Thanks for taking a look on this.

Could you please check does the client actually **sends** a request (using proxy or so)?

Also try to check whether port: 57772 with https: true works. I don’t know what’s the configuration on your side, but if request coming to port 443 is not handled by Caché API then it won’t work.

Thanks!

**Comment by theflyingape** [comment]
My apologies, I just relaunched http/57772, tested SMP access from a browser to it.  The configuration using https: false with port 57772 does not work either.  :(

After Ctrl-Shift P "cos" <enter>, I did a client-side **sudo netstat -pant | grep :57772** and itshwos me only the firefox PID connection, no code outbound TCP attempt listed.

**Comment by ZitRos** [comment]
What does the VSCode cos output say?

**Comment by theflyingape** [comment]
Unfortunately, pressing <enter> after cos comes back and shows nothing.  So, no outbound TCP attempt, no UI changes.  Is there a debug/verbosity flag?

**Comment by ZitRos** [comment]
Changelog just was not updated: check this repository’s commit history to see the messages of changes.

I cannot understand how can I help you. If you can connect to SMP and the Atelier API is opened and accesible, you will definitely be able to connect to Caché with the right settings.

Have you tried **proxying** the call? Have you tried to run local Caché version to see if it works with it? I cannot diagnose what goes wrong because of the lack of information.

1. Please, first, test whether Atelier API is accesible **from the browser** on a **local machine**. Make a simple GET request to any endpoint. ([For example](https://docs.intersystems.com/latest/csp/docbook/DocBook.UI.Page.cls?KEY=GSCF_ref#GSCF_ref_getserver))
2. Then, test whether you can access the same endpoint using HTTPS (again, from the browser).
3. Then, reset the configuration in VSCode to defaults and try to connect to HTTP first with according settings of your server.
4. Then, **the only change** you need is to change `https` to `true`, do not change the port number.

Anyway, if it worked before (v0.0.x) and now it stopped working even via http, the problem is most likely in your configuration.
